name: Github actions demo 2
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GitHub Actions演示
    runs-on: ubuntu-latest
    steps:
      - name: environment prepare stage
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run:
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      - name: Set up Go 1.20 stage
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.20
      - name: Checkout stage
        uses: actions/checkout@master
      - name: build stage
        run: go build -o server .
      - name: Unit test stage
        run: go test -v .
      - name: Deploy stage
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ vars.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          SOURCE: "server"
          TARGET: ${{ vars.REMOTE_TARGET }}
          SSH_OPTIONS: '-o StrictHostKeyChecking=no -v'
