name: Github actions gotest
on:
  push:
    branches:
      - go-test
jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.10

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test ./...
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "your action start"}' https://discord.com/api/webhooks/1304830265511907462/UgGGS9Wdc9sz6gqizUjZXBYgU5NHeKCeZJ_Yk0to_VREBXvQRr-8ix4E7uOBzOQylykY
