name: Github actions gotest
on:
  push:
    branches:
      - go-test
jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1304830265511907462/UgGGS9Wdc9sz6gqizUjZXBYgU5NHeKCeZJ_Yk0to_VREBXvQRr-8ix4E7uOBzOQylykY"

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.10

      - name: Check out code
        uses: actions/checkout@v2

      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "GitHub Actions Workflow Succeeded 🎉"}' $DISCORD_WEBHOOK_URL

      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "GitHub Actions Workflow Failed ❌"}' $DISCORD_WEBHOOK_URL

